import Link from 'next/link';
import { getrich } from "public/data/getrich";
import styles from '@/styles/cartfe.module.css'
import React, { useState, useEffect } from "react";
import dynamic from "next/dynamic";
import Head from 'next/head';
import Navback from '/components/navback';
import Cart from '/components/cart/cart_display';
import Footer from '/components/footer';
import Image from 'next/image';
import { getSession, useSession, signOut } from "next-auth/react";

export default function order({}) {
    
    return (
        <>
        <Head>
            <title>GetFull</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navback/>

            <div className={styles.container}>
                <div className="mt-3">
                    <div className={styles.head}>
                        <p>Keranjangku</p>
                    </div>
                </div>
                <div className={styles.cartcon}>
                    <Cart/>

                </div>
            </div>

        <Footer/>

        </>
    )
}