import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { Inter } from '@next/font/google';
import styles from '@/styles/daftar/daftar.module.css';
import { signIn } from "next-auth/react";
import Link from 'next/link';
import { useState } from 'react';
import { useFormik } from 'formik';
import { useRouter } from 'next/router';

export default function Daftar() {

  const router = useRouter();

  const [phonenumber, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [cpassword, setCpassword] = useState("");
  const [username, setUsername] = useState("");

  const handler = async (e) => {
    e.preventDefault();   

    let pn = phonenumber;
    let u = username;
    let p = password;
    let cp = cpassword;

    console.log(phonenumber,username,password)

    const options = {
      method:"POST",
      headers:{'Content-Type':'application/json'},
      body:JSON.stringify({phonenumber:pn, username:u, password:p, cpassword:cp})
    }

    await fetch('http://localhost:3000/api/auth/signup', options)
      .then(res=>res.json())
      .then((data)=>{
        console.log(data);
        if(data.status)router.push('http://localhost:3000');
        else alert(data.message);
      })

  }

  async function handleGoogleSignin(){
    signIn('google',{callbackUrl: "http://localhost:3000/"})
  }
  



  return (
    <>
      <Head>
        <title>GetFull</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="box position-relative" className="box">
        <div className="position-absolute top-50 start-50 translate-middle">
            <div className={styles.logo}>
              <Image 
              src='/aset/login n signin aset/Getfull.svg' 
              width={150} 
              height={50} 
              />
            </div>
        
            <div className={styles.daftar_main}>
                <div className="daftar_main">
                    <input 
                    type="text" 
                    className={styles.daftar_input} 
                    placeholder="Phone Number"
                    onChange={(e) => setPhone(e.target.value)}
                    />
                </div>

                <div className="daftar_main">
                    <input 
                    type="text" 
                    className={styles.daftar_input} 
                    placeholder="Username"
                    onChange={(e) => setUsername(e.target.value)}
                    />
                </div>
        
                <div className="daftar_main">
                    <input 
                    type="password" 
                    className={styles.daftar_input} 
                    placeholder="Password"
                    onChange={(e) => setPassword(e.target.value)}
                    />
                </div>

                <div className="daftar_main">
                    <input 
                    type="password" 
                    className={styles.daftar_input} 
                    placeholder="Confirm Password"
                    onChange={(e) => setCpassword(e.target.value)}
                    />
                </div>
        
                <div className="buttons">
                    <Link href="/"><button onClick={(e) => handler(e)} className={styles.daftar_btn}>Daftar</button></Link>
                </div>

                <div className={styles.break}>
                  <p>Atau</p>
                </div>

                <div class="buttons">
                        
                        <button className={styles.third_btn} onClick={handleGoogleSignin}>
                            <span className={styles.icon}>
                            <Image 
                            src="/aset/login n signin aset/google.svg" 
                            alt="logo google"
                            width={20}
                            height={20}
                            />
                            </span>
                            &nbsp;
                            Daftar dengan Google
                        </button>
                        
                </div>

                <div className={styles.logask}>
                    Sudah punya akun? <Link href="/" className="golog">Masuk</Link>
                </div>
            </div>
        </div>
      </div>
    </>
  )
}