import Head from 'next/head';
import Navbar from '/components/navbar';
import Footer from '/components/footer';
import Searchbox from '/components/homepage/searchbox';
import Portal from '/components/homepage/getrich_portal';
import Carousel from '/components/homepage/carousel/carousel';
import Slider from '/components/product card/carousel_product_card';
import styles from '@/styles/homepage/homepage.module.css';
import Image from 'next/image';
import { getSession, useSession, signOut } from "next-auth/react";
import React from "react";

export default function Home() {
    return (
        <>
        <Head>
        <title>GetFull</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>

        <main>
        <div className={styles.container}>
            {/* Search box */}
            <div className={styles.searchbox}>
                <Searchbox/>
            </div>

            {/* GetRich Portal */}
            <div className={styles.gr_portal}>
                <Portal/>
            </div>

            {/* Carousel */}
            <div className={styles.carousel_home}>
                <Carousel/>
            </div>

            {/* Product */}
            <div className={styles.product_section}>
                <div className={styles.product_carousel}>
                    <Slider/>
                </div>
            </div>

        </div>
        </main>

        <Footer/>
        </>
    )
}

export async function getServerSideProps({req}){
    const session = await getSession({req})

    if(!session){
        return{
            redirect:{
                destination:'http://localhost:3000',
                permanent:false
            }
        }
    }

    return {
        props: {session}
    }
}
