import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { Inter } from '@next/font/google';
import styles from '@/styles/listmerch.module.css';
import Link from 'next/link';
import Footer from '/components/footer';
import Navbar from '/components/navbar';
import Searchbox from '/components/homepage/searchbox'
import { useState } from 'react';
import { useRouter } from 'next/router';
import { getSession, useSession, signOut } from "next-auth/react"

export default function Daftar() {

    const{ data:session } = useSession()
    function handleSignOut(){
        signOut()
    }


  return (
    <>
      <Head>
        <title>GetFull</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

        <div className={styles.searchbox}>
            <Searchbox/>
        </div>

    <div className={styles.setting_main}>
        <div className='setting_main'>
            <div className={styles.line1}>
                <Image 
                src="/aset/listmerch aset/merch1.svg" 
                alt="image"
                width={48}
                height={48}
                />
                <div className={styles.container}>
                    Resto Makan Enak
                    <div className={styles.small}>
                        Jl. Dimana Saja
                        <br></br>
                        2.2km
                    </div>
                </div>
                <div className={styles.rating}>
                    <Image 
                        src='/aset/listmerch aset/rating.svg' 
                        alt="rating"
                        width={28} 
                        height={36} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}>
                <Image 
                src="/aset/listmerch aset/merch2.svg" 
                alt="image"
                width={48}
                height={48}
                />
                <div className={styles.container}>
                    Resto Makan Enak
                    <div className={styles.small}>
                        Jl. Dimana Saja
                        <br></br>
                        2.2km
                    </div>
                </div>
                <div className={styles.rating}>
                    <Image 
                        src='/aset/listmerch aset/rating.svg' 
                        alt="rating"
                        width={28} 
                        height={36} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}>
                <Image 
                src="/aset/listmerch aset/merch3.svg" 
                alt="image"
                width={48}
                height={48}
                />
                <div className={styles.container}>
                    Resto Makan Enak
                    <div className={styles.small}>
                        Jl. Dimana Saja
                        <br></br>
                        2.2km
                    </div>
                </div>
                <div className={styles.rating}>
                    <Image 
                        src='/aset/listmerch aset/rating.svg' 
                        alt="rating"
                        width={28} 
                        height={36} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}>
                <Image 
                src="/aset/listmerch aset/merch4.svg" 
                alt="image"
                width={48}
                height={48}
                />
                <div className={styles.container}>
                    Resto Makan Enak
                    <div className={styles.small}>
                        Jl. Dimana Saja
                        <br></br>
                        2.2km
                    </div>
                </div>
                <div className={styles.rating}>
                    <Image 
                        src='/aset/listmerch aset/rating.svg' 
                        alt="rating"
                        width={28} 
                        height={36} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}>
                <Image 
                src="/aset/listmerch aset/merch5.svg" 
                alt="image"
                width={48}
                height={48}
                />
                <div className={styles.container}>
                    Resto Makan Enak
                    <div className={styles.small}>
                        Jl. Dimana Saja
                        <br></br>
                        2.2km
                    </div>
                </div>
                <div className={styles.rating}>
                    <Image 
                        src='/aset/listmerch aset/rating.svg' 
                        alt="rating"
                        width={28} 
                        height={36} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}>
                <Image 
                src="/aset/listmerch aset/merch6.svg" 
                alt="image"
                width={48}
                height={48}
                />
                <div className={styles.container}>
                    Resto Makan Enak
                    <div className={styles.small}>
                        Jl. Dimana Saja
                        <br></br>
                        2.2km
                    </div>
                </div>
                <div className={styles.rating}>
                    <Image 
                        src='/aset/listmerch aset/rating.svg' 
                        alt="rating"
                        width={28} 
                        height={36} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}>
                <Image 
                src="/aset/listmerch aset/merch7.svg" 
                alt="image"
                width={48}
                height={48}
                />
                <div className={styles.container}>
                    Resto Makan Enak
                    <div className={styles.small}>
                        Jl. Dimana Saja
                        <br></br>
                        2.2km
                    </div>
                </div>
                <div className={styles.rating}>
                    <Image 
                        src='/aset/listmerch aset/rating.svg' 
                        alt="rating"
                        width={28} 
                        height={36} 
                    />
                </div>
            </div>
        </div>

        <div className='setting_main'>
            <div className={styles.line1}>
                <Image 
                src="/aset/listmerch aset/merch8.svg" 
                alt="image"
                width={48}
                height={48}
                />
                <div className={styles.container}>
                    Resto Makan Enak
                    <div className={styles.small}>
                        Jl. Dimana Saja
                        <br></br>
                        2.2km
                    </div>
                </div>
                <div className={styles.rating}>
                    <Image 
                        src='/aset/listmerch aset/rating.svg' 
                        alt="rating"
                        width={28} 
                        height={36} 
                    />
                </div>
            </div>
        </div>

      </div>
      <Footer/>
    </>
  )
}