import Link from 'next/link';
import { getrich } from "public/data/getrich";
import styles from '@/styles/otw.module.css'
import React, { useState, useEffect } from "react";
import dynamic from "next/dynamic";
import Head from 'next/head';
import Navback from '/components/navback';
import Cart from '/components/cart/cart_display';
import Footer from '/components/footer';
import MapContainer from '/components/map';
import Image from 'next/image';
import { getSession, useSession, signOut } from "next-auth/react";

export default function otw({ getrichh }) {
    
    return (
        <>
        <Head>
            <title>GetFull</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navback/>

            <div className={styles.container}>
                <h4>Orderan kamu sedang berlangsung!</h4>
                <div className={styles.contmap}>
                    <MapContainer />
                </div>
                <div className={styles.cont}>
                    <h3>Driver Handal</h3>
                    <div className={styles.ket}>
                        <div className={styles.keterangan}>
                            Nomor Polisi<br/>AB 1314 H
                        </div>
                        <div className={styles.keterangan}>
                            Estimasi<br/>10 menit
                        </div>
                        <div className={styles.keterangan}>
                            Jarak<br/>1.2 Km
                        </div>
                    </div>
                    <div className={styles.place}>
                        <div className={styles.places}>
                        <Image className={styles.logo}
                                src="/aset/setting aset/merchant.svg" 
                                alt="anda"
                                width={23}
                                height={24}
                            />
                            <h6>Wisdom Park Food<br/></h6>
                            Unnamed Road, Karang Malang, Caturtunggal, Kec. Depok
                        </div>
                        <div className={styles.places}>
                            <Image className={styles.logo}
                                src="/aset/setting aset/loc.svg" 
                                alt="tujuan"
                                width={21}
                                height={26}
                            />
                            <h6>UGM Central Office<br/></h6>
                            69JH+WCH, Karang Malang, Caturtunggal, Depok
                        </div>
                    </div>
                </div>
            </div>

        <Footer/>

        </>
    )
}