import Link from 'next/link';
import { getrich } from "public/data/getrich";
import styles from '@/styles/payment.module.css'
import React, { useState, useEffect } from "react";
import dynamic from "next/dynamic";
import Head from 'next/head';
import Navback from '/components/navback';
import Footer from '/components/footer';
import Image from 'next/image';
import { getSession, useSession, signOut } from "next-auth/react";

export default function payment({ getrichh }) {
    
    return (
        <>
        <Head>
            <title>GetFull</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navback/>

        <main>
            <div className={styles.container}>
                <div className="mt-3">
                    <div className={styles.head}>
                        <p>Pilihan Pembayaran</p>
                    </div>
                <div>
                {getrich.map((getrichh) => (
                    <div className={styles.link}>
                        <Image 
                            src="/aset/setting aset/getrich.svg" 
                            alt="logo"
                            width={30}
                            height={30}
                            className={styles.img}
                        />
                        <div className={styles.card_body}>
                            <h6>GetRich</h6>
                            <p>{getrichh.saldo}</p>
                            
                        </div>
                        <div class="form-check">
                            <input className={styles.check} type="radio" value=""/>
                        </div>
                    </div>
                ))}

        
                <Link href='#'>
                    <div className={styles.topup}>
                        <p>Isi saldo sekarang</p> 
                        </div>
                </Link>

                <div className={styles.link}>
                    <Image 
                        src="/aset/setting aset/cash.svg" 
                        alt="logo"
                        width={30}
                        height={30}
                        className={styles.img}
                    />
                    <div className={styles.cash}>
                        <h6>Cash</h6>                        
                    </div>
                    <div class="form-check">
                        <input className={styles.check} type="radio" value=""/>
                    </div>
                </div>
        
                </div>
                    <footer class="fixed-bottom">
                        <div className={styles.foot}>
                                <p class="text-end">
                                    Total<br/>Rp30.000
                                </p>  
                            <Link href="#">
                                <div className={styles.cekout}>
                                    <h6>Bayar</h6>
                                </div>
                            </Link>
                        </div>
                    </footer>
                </div>
            </div>
        </main>
        </>
    )
}