import Head from 'next/head';
import Navback from '/components/navback';
import Footer from '/components/footer';
import Promo from 'components/promo_display';
import styles from '@/styles/promo.module.css';
import Image from 'next/image';
import { getSession, useSession, signOut } from "next-auth/react";
import React from "react";

export default function promo() {
    return (
        <>
        <Head>
        <title>GetFull</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navback/>

        <main>
        <div className={styles.container}>
            
            <div className="mt-3">
                <Promo/>
            </div>
            
        </div>
        </main>

        </>
    )
}

/*
export async function getServerSideProps({req}){
    const session = await getSession({req})

    if(!session){
        return{
            redirect:{
                destination:'http://localhost:3000',
                permanent:false
            }
        }
    }

    return {
        props: {session}
    }
}
*/