import Link from 'next/link';
import { getrich } from "public/data/getrich";
import styles from '@/styles/ratefood.module.css'
import React, { useState, useEffect } from "react";
import dynamic from "next/dynamic";
import Head from 'next/head';
import Navback from '/components/navback';
import Footer from '/components/footer';
import Image from 'next/image';
import { getSession, useSession, signOut } from "next-auth/react";

export default function ratedrive({ getrichh }) {
    
    return (
        <>
        <Head>
            <title>GetFull</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navback/>

        <main>
            <div className={styles.container}>
                <div className="mt-3">
                    <div className={styles.head}>
                        <p>Nilai Produk</p>
                    </div>
                </div>

                <div className={styles.container1}>

                </div>

                <div className={styles.container2}>
                    <textarea className={styles.input} placeholder='Tulis review disini...'/>
                    <Link href="/homepage">
                        <button className={styles.button}>Kirim dan kembali ke Halaman Utama</button>
                    </Link>
                </div>
            </div>
        </main>
        </>
    )
}
