import Head from 'next/head';
import Navbar from '/components/navbar';
import Footer from '/components/footer';
import Searchbox from '/components/homepage/searchbox';
import Restaurant from 'components/restaurant/restaurant_display';
import styles from '@/styles/restaurant/restaurant.module.css';
import styles1 from '@/styles/components//restaurant/restaurant.module.css'
import styles2 from '@/styles/components/homepage/searchbox.module.css';

import Image from 'next/image';
import { getSession, useSession, signOut } from "next-auth/react";
import React from "react";
import { useState } from 'react';
import { useEffect } from 'react';
import Link from 'next/link';

export default function Resto() {

    
    const [data, setData] = useState([]);
    const [query, setQuery] = useState('');

    useEffect(() => {
        fetch("http://localhost:3000/api/data-usaha", {
            method: "GET"
        }).then((res) => res.json()).then((data) => setData(data.data))
        console.log(data)
    }, []);

    const searchFilter = (data) => { 
        return data.filter(
        (product) => product.namaresto.toLowerCase()
        .replace(/\s+/g, "")
        .includes(query.toLowerCase().replace(/\s+/g, ""))
    )};

    const filtered = searchFilter(data)

    const handleChange = (e) => {
        setQuery(e.target.value)
    }


    return (
        <>
            
        <Head>
        <title>GetFull</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>

        <main>
        <div className={styles.container}>
            <div className="mt-3">
                <Searchbox/>
            </div>
            
            <div className="mt-3">
                <Restaurant/>
            </div>
            
        </div>
        </main>

        <Footer/>
    </>
    )
}

// export async function getServerSideProps({req}){
//     const session = await getSession({req})

//     if(!session){
//         return{
//             redirect:{
//                 destination:'http://localhost:3000',
//                 permanent:false
//             }
//         }
//     }

//     return {
//         props: {session}
//     }
// }